Add missing QFile include
Used since 40d056195bc400bc4e249cd152993000011687c2. I suppose it's
implicitly pulled in some cases, but for me the build fails against
Qt from KDE's patch collection with "libs/handler.cpp:704:5: error:
'QFile' was not declared in this scope;".

(cherry picked from commit 6cac88b61da1277dcb9a801e47f2d69829c68086)