Add missing QQueue include
Used since 64dc6234b6980172bb53084c16a0e4e693d6011a. I suppose it's
implicitly pulled in some cases, but for me the build fails with
"networkmodel.h:126:56: error: field 'm_updateQueue' has incomplete
type 'QQueue<QPair<NetworkModel::ModelChangeType, NetworkModelItem*> >'".