Fix build error caused by bad merge
moc_connectionicon.cpp:294: undefined reference to `ConnectionIcon::airplaneMode() const'

ConnectionIcon doesn't have the airplane mode property anymore.
Also dropping the now useless airplaneModeChanged signal while at it.